---
# GIS.lab WEB - DEVELOPMENT

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    force: yes
    install_recommends: no
    state: latest
  environment: proxy_env


### DEPENDENCIES
# Python
- name: Install GIS.lab Web Python requirements
  pip:
    virtualenv: /home/{{ ansible_ssh_user }}/.virtualenvs/gislab-web
    requirements: "{{ synced_folder }}/server/requirements.txt"
    virtualenv_site_packages: yes
    extra_args: "--download-cache={{ synced_folder }}/dev/cache/pip"
    state: present
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-python

- name: Install GIS.lab Web Python development requirements
  pip:
    virtualenv: /home/{{ ansible_ssh_user }}/.virtualenvs/gislab-web
    requirements: "{{ synced_folder }}/server/requirements-dev.txt"
    virtualenv_site_packages: yes
    extra_args: "--download-cache={{ synced_folder }}/dev/cache/pip"
    state: present
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-python

- name: Add source code on Python path
  shell: >
    export WORKON_HOME="$HOME/.virtualenvs"
    &&
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    &&
    workon gislab-web
    &&
    add2virtualenv server
  args:
    chdir: "{{ synced_folder }}"
    executable: /bin/bash
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-python


# Javascript
- name: Install NVM
  shell: >
    curl {{ nvm_url }}/v{{ nvm_version }}/install.sh
    | bash
  args:
    creates: /home/{{ ansible_ssh_user }}/.nvm/nvm.sh
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript

- name: Install NodeJS
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm install v{{ node_version }}
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript

- name: Install Gulp
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    npm install -g gulp
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript


- name: Create local development directory for Node modules
  file:
    path: /home/{{ ansible_ssh_user }}/dev/node_modules
    state: directory
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript

- name: Symlink Node modules from local development directory
  file:
    src: /home/{{ ansible_ssh_user }}/dev/node_modules
    dest: "{{ synced_folder }}/clients/node_modules"
    state: link
    force: yes
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript

- name: Prune local Node modules for GIS.lab Web clients
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    npm prune
  args:
    chdir: "{{ synced_folder }}/clients"
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript

- name: Install local Node modules for GIS.lab Web clients
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    {{ item }}
  with_items:
    - npm install
    - npm install web
  args:
    chdir: "{{ synced_folder }}/clients"
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - dep-javascript


### SERVER
- name: Create GIS.lab Web project directory
  file:
    path: "/home/{{ ansible_ssh_user }}/deploy/www/devproj"
    state: directory
    recurse: yes
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - server-django


- name: Create GIS.lab Web project
  shell: >
    export WORKON_HOME="$HOME/.virtualenvs"
    &&
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    &&
    workon gislab-web
    &&
    django-admin.py startproject
    --template={{ synced_folder }}/server/webgis/conf/project_template/
    devproj
    /home/{{ ansible_ssh_user }}/deploy/www
  args:
    executable: /bin/bash
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - server-django

- name: Install custom GIS.lab Web project configuration
  template:
    src: django/settings_custom.py.j2
    dest: "/home/{{ ansible_ssh_user }}/deploy/www/devproj/settings_custom.py"
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - server-django

- name: Build GIS.lab Web project database
  django_manage:
    command: migrate
    app_path: "/home/{{ ansible_ssh_user }}/deploy/www"
    settings: devproj.settings
    virtualenv: /home/{{ ansible_ssh_user }}/.virtualenvs/gislab-web
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - server-django

- name: Create superuser account (u-> admin, p-> admin)
  shell: >
    export WORKON_HOME="$HOME/.virtualenvs"
    &&
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    &&
    workon gislab-web
    &&
    echo "from webgis.viewer.models import GislabUser;
    GislabUser.objects.create_superuser('admin', 'admin@gislab.io', 'admin')"
    | python ./manage.py shell
  args:
    chdir: "/home/{{ ansible_ssh_user }}/deploy/www"
    executable: /bin/bash
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - server-django

- name: Create ordinary user account (u-> {{ ansible_ssh_user }}, p -> {{ ansible_ssh_user }})
  shell: >
    export WORKON_HOME="$HOME/.virtualenvs"
    &&
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    &&
    workon gislab-web
    &&
    echo "from webgis.viewer.models import GislabUser;
    GislabUser.objects.create_user('{{ ansible_ssh_user }}', 'user@gislab.io', '{{ ansible_ssh_user }}')"
    | python ./manage.py shell
  args:
    chdir: "/home/{{ ansible_ssh_user }}/deploy/www"
    executable: /bin/bash
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - server-django


### WEB CLIENT
- name: Build GIS.lab Web JS
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    gulp
  args:
    chdir: "{{ synced_folder }}/clients"
  sudo_user: "{{ ansible_ssh_user }}"
  tags:
    - client-web

# vim: set ts=8 sts=2 sw=2 et:
