---

- hosts: all

  roles:
    - { role: basic, tags: ['basic'] }
    - { role: mapserver, tags: ['mapserver'] }
    - { role: gisquick, tags: ['gisquick'] }
    - { role: gisquick-qgis, tags: ['gisquick-qgis'] }
    - {
        role: gisquick-mobile,
        tags: ['gisquick-mobile'],
        when: GISQUICK_CLIENT_MOBILE
    }
    - { role: example-data, tags: ['example-data'] }

# vim: set ts=8 sts=2 sw=2 et:
