---

- hosts: all
  sudo: yes

  roles:
    - { role: basic, tags: ['basic'] }
    - { role: mapserver, tags: ['mapserver'] }
    - { role: gislab-web-dev, tags: ['gislab-web-dev'] }
    - { role: gislab-web-qgis-dev, tags: ['gislab-web-qgis-dev'] }
    - { role: gislab-mobile-dev, tags: ['gislab-mobile-dev'], when: GISLAB_MOBILE }
    - { role: example-data, tags: ['example-data'] }

# vim: set ts=8 sts=2 sw=2 et:
