---
# Perform GIS.lab Web tests

- hosts: all
  sudo: yes


  tasks:
    # Mapserver
    - name: Test WMS GetCapabilies request without project
      shell: >
        curl
        "http://localhost:90/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMS&REQUEST=GetCapabilities"
        | grep 'WMS_Capabilities .* version="1.3.0"'
      ignore_errors: yes
      changed_when: False

    - name: Test WFS GetCapabilies request without project
      shell: >
        curl
        "http://localhost:90/cgi-bin/qgis_mapserv.fcgi?SERVICE=WFS&REQUEST=GetCapabilities"
        | grep 'WFS_Capabilities .* version="1.0.0"'
      ignore_errors: yes
      changed_when: False


  # GIS.lab Web
    - name: Run GIS.lab Web server tests
      django_manage:
        command: test
        app_path: /vagrant/dev/django
        apps: webgis.viewer
        settings: devproj.settings
        virtualenv: /home/{{ ansible_ssh_user }}/.virtualenvs/gislab-web
      sudo_user: "{{ ansible_ssh_user }}"

# vim: set ts=8 sts=2 sw=2 et:
