---
# Perform GIS.lab Web tests

- hosts: all

  vars:
    mapserver_url: http://localhost:90/cgi-bin/qgis_mapserv.fcgi

  tasks:
    # Mapserver
    - name: Test WMS GetCapabilies request without project
      shell: >
        curl
        "{{ mapserver_url }}?SERVICE=WMS&REQUEST=GetCapabilities"
        | grep 'WMS_Capabilities .* version="1.3.0"'
      ignore_errors: yes
      changed_when: False

    - name: Test WFS GetCapabilies request without project
      shell: >
        curl
        "{{ mapserver_url }}?SERVICE=WFS&REQUEST=GetCapabilities"
        | grep 'WFS_Capabilities .* version="1.0.0"'
      ignore_errors: yes
      changed_when: False


    # GIS.lab Web
    - name: Run GIS.lab Web server tests
      django_manage:
        command: test
        app_path: /home/{{ ansible_user }}/deploy/www
        apps: webgis.viewer
        settings: devproj.settings
        virtualenv: /home/{{ ansible_user }}/.virtualenvs/gislab-web

# vim: set ts=8 sts=2 sw=2 et:
