---

- name: service xvfb restart
  service:
    name: xvfb
    state: restarted
  become: yes

- name: service lighttpd restart
  service:
    name: lighttpd
    state: restarted
  become: yes

# vim: set ts=8 sts=2 sw=2 et:
