---
# GIS.lab MOBILE - DEVELOPMENT

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    force: yes
    install_recommends: no
    state: latest
  environment: "{{ proxy_env }}"
  become: yes


### ANDROID
- name: Download Android SDK
  command: >
    wget
    {{ wget_opts }}
    -O {{ synced_folder }}/dev/cache/tar/android-sdk_r{{ android_sdk_version }}-linux.tgz
    {{ android_sdk_url }}/android-sdk_r{{ android_sdk_version }}-linux.tgz
  tags:
    - dep-android

- name: Install Android SDK
  command: >
    tar -xzf
    {{ synced_folder }}/dev/cache/tar/android-sdk_r{{ android_sdk_version }}-linux.tgz
    -C /home/{{ ansible_user }}/dev/apps
  args:
    creates: "{{ android_root }}/tools/android"
  tags:
    - dep-android

- name: Install script for non-interactive Android platform, tools and API installation
  template:
    src: android/android-sdk-install.expect.j2
    dest: /home/{{ ansible_user }}/dev/apps/android-sdk-install.expect
  tags:
    - dep-android

- name: Install Android platform, tools and API
  command: >
    expect /home/{{ ansible_user }}/dev/apps/android-sdk-install.expect
  args:
    creates: "{{ android_root }}/platform-tools/adb"
  tags:
    - dep-android


### CORDOVA
- name: Install Cordova
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    npm install -g cordova@{{ cordova_version }}
  tags:
    - dep-cordova

- name: Install Android platform for Cordova
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    cordova platform add android@{{ cordova_pf_android_version }} || true
  args:
    chdir: "{{ synced_folder }}/clients/mobile/cordova-app"
  tags:
    - dep-cordova

# TODO: specify plugins versions
# TODO: consider using "node tasks/plugins.js" for installing dependencies
# from file
- name: Install Cordova plugins
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    cordova plugin add "{{ item }}"
  with_items:
    - cordova-plugin-device
    - cordova-plugin-splashscreen
    - cordova-plugin-geolocation@0.3.6
    - cordova-plugin-inappbrowser
  args:
    chdir: "{{ synced_folder }}/clients/mobile/cordova-app"
  tags:
    - dep-cordova


### JAVASCRIPT
- name: Install local Node modules for GIS.lab Mobile client
  shell: >
    export NVM_DIR="$HOME/.nvm"
    &&
    . "$NVM_DIR/nvm.sh"
    &&
    nvm use v{{ node_version }}
    &&
    {{ item }}
  with_items:
    - npm install mobile
  args:
    chdir: "{{ synced_folder }}/clients"
  tags:
    - dep-javascript

# vim: set ts=8 sts=2 sw=2 et:
