---
# GIS.lab WEB QGIS PLUGIN - DEVELOPMENT

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    force: yes
    install_recommends: no
    state: latest
  environment: proxy_env

# vim: set ts=8 sts=2 sw=2 et:
