---

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    force: yes
    install_recommends: no
    state: latest
  environment: proxy_env


- name: Install QGIS Mapserver configuration
  template:
    src: mapserver/lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
  notify:
    - service lighttpd restart

- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
